### ISSUE TITLE
npm test failes after update

### ISSUE THREAD

**Issue by baschke** [nkl-kst/MMM-RBB-Weather#12]
Hi,

after the recent update the module doesn't start. The npm test results in:

> MMM-RBB-Weather@1.2.0 test /home/pi/MagicMirror/modules/MMM-RBB-Weather
> nyc mocha "test/unit/**/*.js"
>sh: 1: nyc: not found
>npm ERR! Test failed.  See above for more details.

Any ideas what's wrong?

regards
Christian

**Comment by nkl-kst** [comment]
Hi Christian,

are you running the tests from inside the modules directory? It seems that your process can't find the `nyc` package.

> sh: 1: nyc: not found

You could also try to install `nyc` globally with `npm install -g nyc`.

Best regards

**Comment by baschke** [comment]
yes I'm running the test from the module directory. I installed nyc globally now. The test result is now different but still negative:

pi@raspberrypi:~/MagicMirror/modules/MMM-RBB-Weather $ npm test

> MMM-RBB-Weather@1.2.0 test /home/pi/MagicMirror/modules/MMM-RBB-Weather
> nyc mocha "test/unit/**/*.js"

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn mocha ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:613:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3
npm ERR! Test failed.  See above for more details.

**Comment by nkl-kst** [comment]
Did you install all dev dependencies? Since there are a lot of dependencies for testing, I recommended to just install "production dependencies" in the README by running `npm install --only=prod`.

There is a section called [Developer Notes](https://github.com/nkl-kst/MMM-RBB-Weather#developer-notes) in the README. You need to install all dependencies with `npm install` before running the tests.

But I'm not sure if it works on a Raspberry Pi :confused: Please let me know if you were able to run the tests on your Raspberry.

**Comment by nkl-kst** [comment]
I was able to run unit tests on my Raspberry Pi. Just needed to install all dependencies with `npm install` (this took about 15 minutes, because one lib needs to be compiled) and then run the tests. Note that NodeJS 11 is required.

Do you still have issues?

**Comment by nkl-kst** [comment]
I'm closing this issue for now. Please feel free to reopen it if you still have issues or questions.
